export const GEOLOGICAL_CHARACTERISTICS = {
  proven_basin: {
    name: 'Proven Basin',
    description: 'Mature area with established production (e.g., Permian Basin, North Sea)',
    probability: 0.40,
    leaseCostMultiplier: 1.5,
    seismicCostMultiplier: 1.0,
    explorationWellMultiplier: 1.0,
    developmentWellMultiplier: 1.0,
    facilityMultiplier: 1.0,
    dailyOPEXMultiplier: 1.0,
    reserveRangeMin: 5000000,
    reserveRangeMax: 30000000,
    wellProductivityMultiplier: 1.0,
    declineRateAnnual: 0.08,
    oilQualityWeights: { light: 0.6, medium: 0.3, heavy: 0.1 },
    timeToFirstOil: 18,
    regulatoryRisk: 'low',
    infrastructureAccess: 'excellent',
    marketAccess: 'excellent',
    oilPriceDiscount: 0,
    abandonmentCost: 3000000
  },

  frontier_basin: {
    name: 'Frontier Basin',
    description: 'Underexplored region with theoretical potential (e.g., East Africa, Guyana)',
    probability: 0.15,
    leaseCostMultiplier: 0.3,
    seismicCostMultiplier: 1.5,
    explorationWellMultiplier: 2.0,
    developmentWellMultiplier: 1.8,
    facilityMultiplier: 2.5,
    dailyOPEXMultiplier: 1.5,
    reserveRangeMin: 50000000,
    reserveRangeMax: 200000000,
    wellProductivityMultiplier: 1.3,
    declineRateAnnual: 0.05,
    oilQualityWeights: { light: 0.4, medium: 0.4, heavy: 0.2 },
    timeToFirstOil: 48,
    regulatoryRisk: 'high',
    infrastructureAccess: 'poor',
    marketAccess: 'limited',
    oilPriceDiscount: -5,
    abandonmentCost: 15000000
  },

  deepwater: {
    name: 'Deepwater',
    description: 'Offshore exploration >500m depth (e.g., Gulf of Mexico, Brazil pre-salt)',
    probability: 0.20,
    leaseCostMultiplier: 2.0,
    seismicCostMultiplier: 3.0,
    explorationWellMultiplier: 8.0,
    developmentWellMultiplier: 6.0,
    facilityMultiplier: 5.0,
    dailyOPEXMultiplier: 3.0,
    reserveRangeMin: 100000000,
    reserveRangeMax: 500000000,
    wellProductivityMultiplier: 2.5,
    declineRateAnnual: 0.04,
    oilQualityWeights: { light: 0.7, medium: 0.25, heavy: 0.05 },
    timeToFirstOil: 60,
    regulatoryRisk: 'medium',
    infrastructureAccess: 'limited',
    marketAccess: 'good',
    oilPriceDiscount: 0,
    abandonmentCost: 50000000
  },

  unconventional: {
    name: 'Unconventional',
    description: 'Shale oil, tight oil, or heavy oil (e.g., Bakken, Oil Sands)',
    probability: 0.10,
    leaseCostMultiplier: 0.8,
    seismicCostMultiplier: 1.2,
    explorationWellMultiplier: 1.5,
    developmentWellMultiplier: 1.3,
    facilityMultiplier: 1.5,
    dailyOPEXMultiplier: 2.0,
    reserveRangeMin: 10000000,
    reserveRangeMax: 100000000,
    wellProductivityMultiplier: 0.6,
    declineRateAnnual: 0.15,
    oilQualityWeights: { light: 0.2, medium: 0.3, heavy: 0.5 },
    timeToFirstOil: 24,
    regulatoryRisk: 'medium',
    infrastructureAccess: 'good',
    marketAccess: 'good',
    oilPriceDiscount: -10,
    abandonmentCost: 8000000
  }
};

export const DRILL_SITES = {
  A: { x: 50, y: 35, label: 'Site A — Crest of Anticline', desc: 'Top of the structure. Best trap position, highest probability.', probMod: 0.08, risk: 'Low', color: '#10b981' },
  B: { x: 35, y: 50, label: 'Site B — Western Flank', desc: 'Good structural position but near a fault. Moderate risk.', probMod: 0.02, risk: 'Medium', color: '#f59e0b' },
  C: { x: 65, y: 55, label: 'Site C — Eastern Flank', desc: 'Amplitude anomaly detected. Promising but uncertain seal.', probMod: 0.0, risk: 'Medium-High', color: '#f97316' },
  D: { x: 50, y: 70, label: 'Site D — Downdip Position', desc: 'Below the main closure. Low probability but possible stratigraphic trap.', probMod: -0.08, risk: 'High', color: '#ef4444' },
};
